echo off
cls
echo ÚÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
echo ³Call you the NICECODE optimizer whit this .BAT file to easy your work.³
echo ³In this file you must be identify the path where can be search        ³
echo ³the INCLUDE files and the .NG language instructions file.             ³
echo ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

c:\comp\pb\nc\nicecode %1 %2 %3 %4 %5 %6 /P-c:\comp\pb;c:\comp\pb\bas;c:\comp\pb\inc;c:\comp\pb\nc;c:\comp\pb\pc
